{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DKLog"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/openweathersdk\/dklog"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openweathersdk\/dklog"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.daksh.OpenWeatherSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.daksh.OpenWeatherSDK\/objc(pl)NSObject","doc:\/\/com.daksh.OpenWeatherSDK\/s7CVarArgP","doc:\/\/com.daksh.OpenWeatherSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.daksh.OpenWeatherSDK\/s23CustomStringConvertibleP","doc:\/\/com.daksh.OpenWeatherSDK\/SQ","doc:\/\/com.daksh.OpenWeatherSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/DKLog","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Logs messages with customizable options, such as log type, mode, and additional information."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DKLog"}],"title":"DKLog","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@OpenWeatherSDK@objc(cs)DKLog","modules":[{"name":"OpenWeatherSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DKLog"}]},"hierarchy":{"paths":[["doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK"]]},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/DKLog\/setMode(_:)"]},{"title":"Enumerations","identifiers":["doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/DKLog\/Mode"]}],"references":{"doc://com.daksh.OpenWeatherSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/SQ"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/DKLog/setMode(_:)":{"role":"symbol","title":"setMode(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Mode","preciseIdentifier":"s:14OpenWeatherSDK5DKLogC4ModeO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/DKLog\/setMode(_:)","kind":"symbol","type":"topic","url":"\/documentation\/openweathersdk\/dklog\/setmode(_:)"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/DKLog/Mode":{"role":"symbol","title":"DKLog.Mode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Mode"}],"abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/DKLog\/Mode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Mode"}],"url":"\/documentation\/openweathersdk\/dklog\/mode"},"doc://com.daksh.OpenWeatherSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/s23CustomStringConvertibleP"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/DKLog/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/DKLog\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/openweathersdk\/dklog\/init"},"doc://com.daksh.OpenWeatherSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/SH"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/DKLog":{"role":"symbol","title":"DKLog","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DKLog"}],"abstract":[{"type":"text","text":"Logs messages with customizable options, such as log type, mode, and additional information."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/DKLog","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DKLog"}],"url":"\/documentation\/openweathersdk\/dklog"},"doc://com.daksh.OpenWeatherSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/objc(pl)NSObject"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK":{"role":"collection","title":"OpenWeatherSDK","abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK","kind":"symbol","type":"topic","url":"\/documentation\/openweathersdk"},"doc://com.daksh.OpenWeatherSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/s7CVarArgP"},"doc://com.daksh.OpenWeatherSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/s28CustomDebugStringConvertibleP"},"doc://com.daksh.OpenWeatherSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DKLog"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DKLog"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DKLog"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/DKLog\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.daksh.OpenWeatherSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DKLog"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1DKLog\/title","value":"DKLog"},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1DKLog\/fragments","value":[{"kind":"identifier","text":"DKLog"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}