{"variants":[{"paths":["\/documentation\/openweathersdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openweathersdk"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/CompositeTrustEvaluator","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/DKLog","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/DefaultTrustEvaluator","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/DisabledEvaluator","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/ForecastParameter","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/OpenWeatherSDK","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/PinnedCertificatesTrustEvaluator","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/PublicKeysTrustEvaluator","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/RevocationTrustEvaluator","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/ServerTrustManager","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/URLEncodedFormEncoder","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/WeatherParameter","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/WeatherService"]},{"title":"Protocols","identifiers":["doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/APIExtended","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/ParameterEncoding","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/ServerTrustEvaluating","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/URLConvertible","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/URLRequestConvertible"]},{"title":"Structures","identifiers":["doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/APIExtension","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/APIFailureResponse","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/APIService","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/City","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/Clouds","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/Coord","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPHeader","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPHeaders","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPMethod","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/JSONEncoding","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/Main","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/System","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/URLEncoding","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/Weather","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/WeatherData","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/WeatherForecast","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/Wind"]},{"title":"Variables","identifiers":["doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/WeatherSDKVersionNumber"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/Parameters"]},{"title":"Enumerations","identifiers":["doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/APIError","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPStatusCode"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"OpenWeatherSDK","title":"OpenWeatherSDK","symbolKind":"module","role":"collection","modules":[{"name":"OpenWeatherSDK"}]},"hierarchy":{"paths":[[]]},"references":{"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/Weather":{"role":"symbol","title":"Weather","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Weather"}],"abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/Weather","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Weather"}],"url":"\/documentation\/openweathersdk\/weather"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/URLRequestConvertible":{"role":"symbol","title":"URLRequestConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"URLRequestConvertible"}],"abstract":[{"type":"text","text":"Types adopting the "},{"type":"codeVoice","code":"URLRequestConvertible"},{"type":"text","text":" protocol can be used to safely construct "},{"type":"codeVoice","code":"URLRequest"},{"type":"text","text":"s."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/URLRequestConvertible","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"URLRequestConvertible"}],"url":"\/documentation\/openweathersdk\/urlrequestconvertible"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/HTTPMethod":{"role":"symbol","title":"HTTPMethod","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPMethod"}],"abstract":[{"type":"text","text":"Type representing HTTP methods. Raw "},{"type":"codeVoice","code":"String"},{"type":"text","text":" value is stored and compared case-sensitively, so"},{"type":"text","text":" "},{"type":"codeVoice","code":"HTTPMethod.get != HTTPMethod(rawValue: \"get\")"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPMethod"}],"url":"\/documentation\/openweathersdk\/httpmethod"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/URLEncoding":{"role":"symbol","title":"URLEncoding","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"URLEncoding"}],"abstract":[{"type":"text","text":"Creates a url-encoded query string to be set as or appended to any existing URL query string or set as the HTTP"},{"type":"text","text":" "},{"type":"text","text":"body of the URL request. Whether the query string is set or appended to any existing URL query string or set as"},{"type":"text","text":" "},{"type":"text","text":"the HTTP body depends on the destination of the encoding."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/URLEncoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"URLEncoding"}],"url":"\/documentation\/openweathersdk\/urlencoding"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/OpenWeatherSDK":{"role":"symbol","title":"OpenWeatherSDK","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenWeatherSDK"}],"abstract":[{"type":"text","text":"A class representing the OpenWeatherSDK, which provides functionality to configure the SDK, set the API key, and check the validity of the API key."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/OpenWeatherSDK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenWeatherSDK"}],"url":"\/documentation\/openweathersdk\/openweathersdk"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/WeatherData":{"role":"symbol","title":"WeatherData","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"WeatherData"}],"abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/WeatherData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WeatherData"}],"url":"\/documentation\/openweathersdk\/weatherdata"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/City":{"role":"symbol","title":"City","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"City"}],"abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/City","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"City"}],"url":"\/documentation\/openweathersdk\/city"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/ServerTrustEvaluating":{"role":"symbol","title":"ServerTrustEvaluating","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ServerTrustEvaluating"}],"abstract":[{"type":"text","text":"A protocol describing the API used to evaluate server trusts."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/ServerTrustEvaluating","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ServerTrustEvaluating"}],"url":"\/documentation\/openweathersdk\/servertrustevaluating"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/ServerTrustManager":{"role":"symbol","title":"ServerTrustManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ServerTrustManager"}],"abstract":[{"type":"text","text":"Responsible for managing the mapping of "},{"type":"codeVoice","code":"ServerTrustEvaluating"},{"type":"text","text":" values to given hosts."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/ServerTrustManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ServerTrustManager"}],"url":"\/documentation\/openweathersdk\/servertrustmanager"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/PublicKeysTrustEvaluator":{"role":"symbol","title":"PublicKeysTrustEvaluator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PublicKeysTrustEvaluator"}],"abstract":[{"type":"text","text":"Uses the pinned public keys to validate the server trust. The server trust is considered valid if one of the pinned"},{"type":"text","text":" "},{"type":"text","text":"public keys match one of the server certificate public keys. By validating both the certificate chain and host,"},{"type":"text","text":" "},{"type":"text","text":"public key pinning provides a very secure form of server trust validation mitigating most, if not all, MITM attacks."},{"type":"text","text":" "},{"type":"text","text":"Applications are encouraged to always validate the host and require a valid certificate chain in production"},{"type":"text","text":" "},{"type":"text","text":"environments."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/PublicKeysTrustEvaluator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PublicKeysTrustEvaluator"}],"url":"\/documentation\/openweathersdk\/publickeystrustevaluator"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/DisabledEvaluator":{"role":"symbol","title":"DisabledEvaluator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisabledEvaluator"}],"abstract":[{"type":"text","text":"Disables all evaluation which in turn will always consider any server trust as valid."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/DisabledEvaluator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisabledEvaluator"}],"url":"\/documentation\/openweathersdk\/disabledevaluator"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/ForecastParameter":{"role":"symbol","title":"ForecastParameter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ForecastParameter"}],"abstract":[{"type":"text","text":"A data structure representing the parameters for requesting weather forecast data."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/ForecastParameter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ForecastParameter"}],"url":"\/documentation\/openweathersdk\/forecastparameter"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/URLConvertible":{"role":"symbol","title":"URLConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"URLConvertible"}],"abstract":[{"type":"text","text":"Types adopting the "},{"type":"codeVoice","code":"URLConvertible"},{"type":"text","text":" protocol can be used to construct "},{"type":"codeVoice","code":"URL"},{"type":"text","text":"s, which can then be used to construct"},{"type":"text","text":" "},{"type":"codeVoice","code":"URLRequests"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/URLConvertible","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"URLConvertible"}],"url":"\/documentation\/openweathersdk\/urlconvertible"},"http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml":{"title":"IANA HTTP status code registry","titleInlineContent":[{"type":"text","text":"IANA HTTP status code registry"}],"type":"link","identifier":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml","url":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/APIExtension":{"role":"symbol","title":"APIExtension","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIExtension"}],"abstract":[{"type":"text","text":"Type that acts as a generic extension point for all "},{"type":"codeVoice","code":"APIExtended"},{"type":"text","text":" types."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/APIExtension","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"APIExtension"}],"url":"\/documentation\/openweathersdk\/apiextension"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/Coord":{"role":"symbol","title":"Coord","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Coord"}],"abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/Coord","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Coord"}],"url":"\/documentation\/openweathersdk\/coord"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/DefaultTrustEvaluator":{"role":"symbol","title":"DefaultTrustEvaluator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultTrustEvaluator"}],"abstract":[{"type":"text","text":"An evaluator which uses the default server trust evaluation while allowing you to control whether to validate the"},{"type":"text","text":" "},{"type":"text","text":"host provided by the challenge. Applications are encouraged to always validate the host in production environments"},{"type":"text","text":" "},{"type":"text","text":"to guarantee the validity of the server’s certificate chain."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/DefaultTrustEvaluator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DefaultTrustEvaluator"}],"url":"\/documentation\/openweathersdk\/defaulttrustevaluator"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/WeatherParameter":{"role":"symbol","title":"WeatherParameter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WeatherParameter"}],"abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/WeatherParameter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WeatherParameter"}],"url":"\/documentation\/openweathersdk\/weatherparameter"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/APIExtended":{"role":"symbol","title":"APIExtended","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIExtended"}],"abstract":[{"type":"text","text":"Protocol describing the "},{"type":"codeVoice","code":"ax"},{"type":"text","text":" extension points for API extended types."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/APIExtended","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"APIExtended"}],"url":"\/documentation\/openweathersdk\/apiextended"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/JSONEncoding":{"role":"symbol","title":"JSONEncoding","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONEncoding"}],"abstract":[{"type":"text","text":"Uses "},{"type":"codeVoice","code":"JSONSerialization"},{"type":"text","text":" to create a JSON representation of the parameters object, which is set as the body of the"},{"type":"text","text":" "},{"type":"text","text":"request. The "},{"type":"codeVoice","code":"Content-Type"},{"type":"text","text":" HTTP header field of an encoded request is set to "},{"type":"codeVoice","code":"application\/json"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/JSONEncoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JSONEncoding"}],"url":"\/documentation\/openweathersdk\/jsonencoding"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/Main":{"role":"symbol","title":"Main","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Main"}],"abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/Main","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Main"}],"url":"\/documentation\/openweathersdk\/main"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/WeatherForecast":{"role":"symbol","title":"WeatherForecast","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"WeatherForecast"}],"abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/WeatherForecast","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WeatherForecast"}],"url":"\/documentation\/openweathersdk\/weatherforecast"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/Clouds":{"role":"symbol","title":"Clouds","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Clouds"}],"abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/Clouds","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Clouds"}],"url":"\/documentation\/openweathersdk\/clouds"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/WeatherService":{"role":"symbol","title":"WeatherService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WeatherService"}],"abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/WeatherService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WeatherService"}],"url":"\/documentation\/openweathersdk\/weatherservice"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/APIError":{"role":"symbol","title":"APIError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIError"}],"abstract":[{"type":"codeVoice","code":"APIError"},{"type":"text","text":" is the error type returned. It encompasses a few different types of errors, each with"},{"type":"text","text":" "},{"type":"text","text":"their own associated reasons."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/APIError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"APIError"}],"url":"\/documentation\/openweathersdk\/apierror"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/Parameters":{"role":"symbol","title":"Parameters","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Parameters"}],"abstract":[{"type":"text","text":"A dictionary of parameters to apply to a "},{"type":"codeVoice","code":"URLRequest"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/Parameters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Parameters"}],"url":"\/documentation\/openweathersdk\/parameters"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/URLEncodedFormEncoder":{"role":"symbol","title":"URLEncodedFormEncoder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"URLEncodedFormEncoder"}],"abstract":[{"type":"text","text":"An object that encodes instances into URL-encoded query strings."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/URLEncodedFormEncoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"URLEncodedFormEncoder"}],"url":"\/documentation\/openweathersdk\/urlencodedformencoder"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/APIService":{"role":"symbol","title":"APIService","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIService"}],"abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/APIService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"APIService"}],"url":"\/documentation\/openweathersdk\/apiservice"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/ParameterEncoding":{"role":"symbol","title":"ParameterEncoding","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParameterEncoding"}],"abstract":[{"type":"text","text":"A type used to define how a set of parameters are applied to a "},{"type":"codeVoice","code":"URLRequest"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/ParameterEncoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ParameterEncoding"}],"url":"\/documentation\/openweathersdk\/parameterencoding"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/HTTPStatusCode":{"role":"symbol","title":"HTTPStatusCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPStatusCode"}],"abstract":[{"type":"text","text":"HTTP status codes as per the "},{"type":"reference","isActive":true,"identifier":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPStatusCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCode"}],"url":"\/documentation\/openweathersdk\/httpstatuscode"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/HTTPHeaders":{"role":"symbol","title":"HTTPHeaders","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPHeaders"}],"abstract":[{"type":"text","text":"An order-preserving and case-insensitive representation of HTTP headers."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPHeaders","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPHeaders"}],"url":"\/documentation\/openweathersdk\/httpheaders"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/CompositeTrustEvaluator":{"role":"symbol","title":"CompositeTrustEvaluator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompositeTrustEvaluator"}],"abstract":[{"type":"text","text":"Uses the provided evaluators to validate the server trust. The trust is only considered valid if all of the"},{"type":"text","text":" "},{"type":"text","text":"evaluators consider it valid."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/CompositeTrustEvaluator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CompositeTrustEvaluator"}],"url":"\/documentation\/openweathersdk\/compositetrustevaluator"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK":{"role":"collection","title":"OpenWeatherSDK","abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK","kind":"symbol","type":"topic","url":"\/documentation\/openweathersdk"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/Wind":{"role":"symbol","title":"Wind","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wind"}],"abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/Wind","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Wind"}],"url":"\/documentation\/openweathersdk\/wind"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/WeatherSDKVersionString":{"role":"symbol","title":"WeatherSDKVersionString","fragments":[{"kind":"identifier","text":"WeatherSDKVersionString"}],"abstract":[{"type":"text","text":"Project version string for OpenWeatherSDK."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/WeatherSDKVersionString","kind":"symbol","type":"topic","url":"\/documentation\/openweathersdk\/weathersdkversionstring"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/RevocationTrustEvaluator":{"role":"symbol","title":"RevocationTrustEvaluator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RevocationTrustEvaluator"}],"abstract":[{"type":"text","text":"An evaluator which Uses the default and revoked server trust evaluations allowing you to control whether to validate"},{"type":"text","text":" "},{"type":"text","text":"the host provided by the challenge as well as specify the revocation flags for testing for revoked certificates."},{"type":"text","text":" "},{"type":"text","text":"Apple platforms did not start testing for revoked certificates automatically until iOS 10.1, macOS 10.12 and tvOS"},{"type":"text","text":" "},{"type":"text","text":"10.1 which is demonstrated in our TLS tests. Applications are encouraged to always validate the host in production"},{"type":"text","text":" "},{"type":"text","text":"environments to guarantee the validity of the server’s certificate chain."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/RevocationTrustEvaluator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RevocationTrustEvaluator"}],"url":"\/documentation\/openweathersdk\/revocationtrustevaluator"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/APIFailureResponse":{"role":"symbol","title":"APIFailureResponse","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIFailureResponse"}],"abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/APIFailureResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"APIFailureResponse"}],"url":"\/documentation\/openweathersdk\/apifailureresponse"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/System":{"role":"symbol","title":"System","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"System"}],"abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/System","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"System"}],"url":"\/documentation\/openweathersdk\/system"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/DKLog":{"role":"symbol","title":"DKLog","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DKLog"}],"abstract":[{"type":"text","text":"Logs messages with customizable options, such as log type, mode, and additional information."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/DKLog","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DKLog"}],"url":"\/documentation\/openweathersdk\/dklog"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/PinnedCertificatesTrustEvaluator":{"role":"symbol","title":"PinnedCertificatesTrustEvaluator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PinnedCertificatesTrustEvaluator"}],"abstract":[{"type":"text","text":"Uses the pinned certificates to validate the server trust. The server trust is considered valid if one of the pinned"},{"type":"text","text":" "},{"type":"text","text":"certificates match one of the server certificates. By validating both the certificate chain and host, certificate"},{"type":"text","text":" "},{"type":"text","text":"pinning provides a very secure form of server trust validation mitigating most, if not all, MITM attacks."},{"type":"text","text":" "},{"type":"text","text":"Applications are encouraged to always validate the host and require a valid certificate chain in production"},{"type":"text","text":" "},{"type":"text","text":"environments."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/PinnedCertificatesTrustEvaluator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PinnedCertificatesTrustEvaluator"}],"url":"\/documentation\/openweathersdk\/pinnedcertificatestrustevaluator"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/HTTPHeader":{"role":"symbol","title":"HTTPHeader","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPHeader"}],"abstract":[{"type":"text","text":"A representation of a single HTTP header’s name \/ value pair."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPHeader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPHeader"}],"url":"\/documentation\/openweathersdk\/httpheader"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/WeatherSDKVersionNumber":{"role":"symbol","title":"WeatherSDKVersionNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"WeatherSDKVersionNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Project version number for OpenWeatherSDK."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/WeatherSDKVersionNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WeatherSDKVersionNumber"}],"url":"\/documentation\/openweathersdk\/weathersdkversionnumber"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/DKLog"]},{"title":"Variables","identifiers":["doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/WeatherSDKVersionNumber","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/WeatherSDKVersionString"]},{"title":"Enumerations","identifiers":["doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPStatusCode"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1HTTPStatusCode\/title","value":"HTTPStatusCode"},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1HTTPStatusCode\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1DKLog\/title","value":"DKLog"},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1DKLog\/fragments","value":[{"kind":"identifier","text":"DKLog"}]},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1WeatherSDKVersionNumber\/title","value":"WeatherSDKVersionNumber"},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1WeatherSDKVersionNumber\/fragments","value":[{"kind":"identifier","text":"WeatherSDKVersionNumber"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}