{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"forbidden"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/openweathersdk\/httpstatuscode\/forbidden"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openweathersdk\/httpstatuscode\/forbidden"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPStatusCode\/forbidden","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Forbidden: 403"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"forbidden"}],"title":"HTTPStatusCode.forbidden","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@OpenWeatherSDK@E@HTTPStatusCode@HTTPStatusCodeForbidden","modules":[{"name":"OpenWeatherSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeForbidden"}]},"hierarchy":{"paths":[["doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPStatusCode"]]},"references":{"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK":{"role":"collection","title":"OpenWeatherSDK","abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK","kind":"symbol","type":"topic","url":"\/documentation\/openweathersdk"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/HTTPStatusCode/forbidden":{"role":"symbol","title":"HTTPStatusCode.forbidden","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"forbidden"}],"abstract":[{"type":"text","text":"Forbidden: 403"}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPStatusCode\/forbidden","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeForbidden"}],"url":"\/documentation\/openweathersdk\/httpstatuscode\/forbidden"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/HTTPStatusCode":{"role":"symbol","title":"HTTPStatusCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPStatusCode"}],"abstract":[{"type":"text","text":"HTTP status codes as per the "},{"type":"reference","isActive":true,"identifier":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPStatusCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCode"}],"url":"\/documentation\/openweathersdk\/httpstatuscode"},"http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml":{"title":"IANA HTTP status code registry","titleInlineContent":[{"type":"text","text":"IANA HTTP status code registry"}],"type":"link","identifier":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml","url":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HTTPStatusCodeForbidden"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeForbidden"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HTTPStatusCodeForbidden"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1HTTPStatusCode~1forbidden\/title","value":"HTTPStatusCodeForbidden"},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1HTTPStatusCode~1forbidden\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeForbidden"}]},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1HTTPStatusCode\/title","value":"HTTPStatusCode"},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1HTTPStatusCode\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}