{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(HTTPStatusCodeIISRetryWith) "},{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"iisRetryWith"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The server cannot honour the request because the user has not provided the required information."}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Category"}]},{"type":"text","text":": Internet Information Services"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/openweathersdk\/httpstatuscode\/iisretrywith"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openweathersdk\/httpstatuscode\/iisretrywith"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPStatusCode\/iisRetryWith","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"IIS Retry With: 449"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"iisRetryWith"}],"title":"HTTPStatusCode.iisRetryWith","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@OpenWeatherSDK@E@HTTPStatusCode@HTTPStatusCodeIISRetryWith","modules":[{"name":"OpenWeatherSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeIISRetryWith"}]},"hierarchy":{"paths":[["doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPStatusCode"]]},"references":{"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK":{"role":"collection","title":"OpenWeatherSDK","abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK","kind":"symbol","type":"topic","url":"\/documentation\/openweathersdk"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/HTTPStatusCode":{"role":"symbol","title":"HTTPStatusCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPStatusCode"}],"abstract":[{"type":"text","text":"HTTP status codes as per the "},{"type":"reference","isActive":true,"identifier":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPStatusCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCode"}],"url":"\/documentation\/openweathersdk\/httpstatuscode"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/HTTPStatusCode/iisRetryWith":{"role":"symbol","title":"HTTPStatusCode.iisRetryWith","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"iisRetryWith"}],"abstract":[{"type":"text","text":"IIS Retry With: 449"}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPStatusCode\/iisRetryWith","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeIISRetryWith"}],"url":"\/documentation\/openweathersdk\/httpstatuscode\/iisretrywith"},"http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml":{"title":"IANA HTTP status code registry","titleInlineContent":[{"type":"text","text":"IANA HTTP status code registry"}],"type":"link","identifier":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml","url":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HTTPStatusCodeIISRetryWith"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeIISRetryWith"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HTTPStatusCodeIISRetryWith"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1HTTPStatusCode\/title","value":"HTTPStatusCode"},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1HTTPStatusCode\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1HTTPStatusCode~1iisRetryWith\/title","value":"HTTPStatusCodeIISRetryWith"},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1HTTPStatusCode~1iisRetryWith\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeIISRetryWith"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}