{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"siteIsFrozen"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Used by the "},{"type":"reference","isActive":true,"identifier":"https:\/\/en.wikipedia.org\/wiki\/Pantheon_(software)"},{"type":"text","text":" web platform to indicate a site that has been frozen due to inactivity."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/openweathersdk\/httpstatuscode\/siteisfrozen"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openweathersdk\/httpstatuscode\/siteisfrozen"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPStatusCode\/siteIsFrozen","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Site is frozen: 530"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"siteIsFrozen"}],"title":"HTTPStatusCode.siteIsFrozen","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@OpenWeatherSDK@E@HTTPStatusCode@HTTPStatusCodeSiteIsFrozen","modules":[{"name":"OpenWeatherSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeSiteIsFrozen"}]},"hierarchy":{"paths":[["doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPStatusCode"]]},"references":{"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK":{"role":"collection","title":"OpenWeatherSDK","abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK","kind":"symbol","type":"topic","url":"\/documentation\/openweathersdk"},"http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml":{"title":"IANA HTTP status code registry","titleInlineContent":[{"type":"text","text":"IANA HTTP status code registry"}],"type":"link","identifier":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml","url":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/HTTPStatusCode/siteIsFrozen":{"role":"symbol","title":"HTTPStatusCode.siteIsFrozen","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"siteIsFrozen"}],"abstract":[{"type":"text","text":"Site is frozen: 530"}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPStatusCode\/siteIsFrozen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeSiteIsFrozen"}],"url":"\/documentation\/openweathersdk\/httpstatuscode\/siteisfrozen"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/HTTPStatusCode":{"role":"symbol","title":"HTTPStatusCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPStatusCode"}],"abstract":[{"type":"text","text":"HTTP status codes as per the "},{"type":"reference","isActive":true,"identifier":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPStatusCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCode"}],"url":"\/documentation\/openweathersdk\/httpstatuscode"},"https://en.wikipedia.org/wiki/Pantheon_(software)":{"title":"Pantheon","titleInlineContent":[{"type":"text","text":"Pantheon"}],"type":"link","identifier":"https:\/\/en.wikipedia.org\/wiki\/Pantheon_(software)","url":"https:\/\/en.wikipedia.org\/wiki\/Pantheon_(software)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HTTPStatusCodeSiteIsFrozen"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeSiteIsFrozen"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HTTPStatusCodeSiteIsFrozen"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1HTTPStatusCode~1siteIsFrozen\/title","value":"HTTPStatusCodeSiteIsFrozen"},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1HTTPStatusCode~1siteIsFrozen\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeSiteIsFrozen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1HTTPStatusCode\/title","value":"HTTPStatusCode"},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1HTTPStatusCode\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}