{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(HTTPStatusCodeURITooLong) "},{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"uriTooLong"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/openweathersdk\/httpstatuscode\/uritoolong"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openweathersdk\/httpstatuscode\/uritoolong"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPStatusCode\/uriTooLong","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"URI Too Long: 414"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"uriTooLong"}],"title":"HTTPStatusCode.uriTooLong","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@OpenWeatherSDK@E@HTTPStatusCode@HTTPStatusCodeURITooLong","modules":[{"name":"OpenWeatherSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeURITooLong"}]},"hierarchy":{"paths":[["doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK","doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPStatusCode"]]},"references":{"http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml":{"title":"IANA HTTP status code registry","titleInlineContent":[{"type":"text","text":"IANA HTTP status code registry"}],"type":"link","identifier":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml","url":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/HTTPStatusCode":{"role":"symbol","title":"HTTPStatusCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPStatusCode"}],"abstract":[{"type":"text","text":"HTTP status codes as per the "},{"type":"reference","isActive":true,"identifier":"http:\/\/www.iana.org\/assignments\/http-status-codes\/http-status-codes.xhtml"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPStatusCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCode"}],"url":"\/documentation\/openweathersdk\/httpstatuscode"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK/HTTPStatusCode/uriTooLong":{"role":"symbol","title":"HTTPStatusCode.uriTooLong","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"uriTooLong"}],"abstract":[{"type":"text","text":"URI Too Long: 414"}],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK\/HTTPStatusCode\/uriTooLong","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPStatusCodeURITooLong"}],"url":"\/documentation\/openweathersdk\/httpstatuscode\/uritoolong"},"doc://com.daksh.OpenWeatherSDK/documentation/OpenWeatherSDK":{"role":"collection","title":"OpenWeatherSDK","abstract":[],"identifier":"doc:\/\/com.daksh.OpenWeatherSDK\/documentation\/OpenWeatherSDK","kind":"symbol","type":"topic","url":"\/documentation\/openweathersdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HTTPStatusCodeURITooLong"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeURITooLong"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HTTPStatusCodeURITooLong"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1HTTPStatusCode\/title","value":"HTTPStatusCode"},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1HTTPStatusCode\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1HTTPStatusCode~1uriTooLong\/title","value":"HTTPStatusCodeURITooLong"},{"op":"replace","path":"\/references\/doc:~1~1com.daksh.OpenWeatherSDK~1documentation~1OpenWeatherSDK~1HTTPStatusCode~1uriTooLong\/fragments","value":[{"kind":"identifier","text":"HTTPStatusCodeURITooLong"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}